exclude: tests/fixtures

default_stages: [commit, manual]
default_install_hook_types: ["pre-commit", "commit-msg"]
repos:
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
      - id: djcss
        exclude: 'static/admin/css/vendor/select2/select2.min.css'
      - id: djjs
        exclude: 'static/admin/js/vendor/(jquery/jquery.min.js|select2/select2.full.min.js|xregexp/xregexp.js|xregexp/xregexp.min.js)'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --unsafe-fixes]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: no-commit-to-branch
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [markdown]
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        name: Run MyPy typing checks.
        additional_dependencies:
          - protobuf
          - grpc-stubs
          - types-protobuf
          - mypy-protobuf
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
