# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/track_content_difference.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%protos/track_content_difference.proto\x12\x18track_content_difference"\x10\n\x0eTriggerRequest"3\n\x0fTriggerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x97\x01\n\x1dTrackContentDifferenceService\x12v\n\x1dTriggerTrackContentDifference\x12(.track_content_difference.TriggerRequest\x1a).track_content_difference.TriggerResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "protos.track_content_difference_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRIGGERREQUEST"]._serialized_start = 67
    _globals["_TRIGGERREQUEST"]._serialized_end = 83
    _globals["_TRIGGERRESPONSE"]._serialized_start = 85
    _globals["_TRIGGERRESPONSE"]._serialized_end = 136
    _globals["_TRACKCONTENTDIFFERENCESERVICE"]._serialized_start = 139
    _globals["_TRACKCONTENTDIFFERENCESERVICE"]._serialized_end = 290
# @@protoc_insertion_point(module_scope)
